#program to input name, age and class
name = input("Enter the name of student = ")
age = input("Enter the age of student = ")
clas = input("Enter the class of student = ")
print("Name= ",name,"    Age= ",age,"    Class= ",clas)
print()
print()
print("Name = ",name)
print("Age = ",age)
print("Class =",clas)
